# Netlify Build Settings
[build]
  command = "npm ci && npm run build" # Use the command that worked
  publish = "dist"                  # Folder Vite builds into
  functions = "netlify/functions"     # Where your Netlify function lives

# Single Page App Rewrite Rule (This fixes the 404 errors)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 # Important: Serve index.html, don't redirect browser
