# Netlify Build Settings
[build]
  command = "npm run build" # Or "npm ci && npm run build"
  publish = "dist"          # The folder Vite builds into
  functions = "netlify/functions" # Where your Netlify function lives

# Single Page App Rewrite Rule (Crucial Part)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 # Serve index.html directly, not a 301/302 redirect
```

**Next Steps:**

1.  **Create the File:** In the root folder of your project (`C:\Users\m4ndi\field-erp.com`), create a new file named exactly `netlify.toml`.
2.  **Add Code:** Copy the code from the file block above and paste it into your new `netlify.toml` file.
3.  **Save** the file.
4.  **Commit and Push:** Add this new file to Git, commit it, and push it to your repository:
    ```bash
    git status # Should show netlify.toml as untracked
    git add netlify.toml
    git commit -m "feat: Add netlify.toml with SPA rewrite rule"
    git push origin main
    

